
export class EditorAudio {
    constructor(editor) {
        this.editor = editor;
        this.assetManager = editor.assetManager;
        this.selectedAsset = null;
        this.previewAudio = null;

        // Injetar HTML do Modal se não existir
        this.injetarModal();

        // Elementos DOM
        this.modal = document.getElementById('modal-audio-editor');
        this.lista = document.getElementById('audio-list');
        this.search = document.getElementById('audio-search');

        this.contentArea = document.getElementById('audio-editor-content');
        this.emptyArea = document.getElementById('audio-editor-empty');

        this.lblNome = document.getElementById('audio-selected-name');
        this.lblId = document.getElementById('audio-selected-id');

        this.sliderVol = document.getElementById('audio-vol-slider');
        this.valVol = document.getElementById('audio-vol-val');

        this.btnPlay = document.getElementById('btn-audio-play');
        this.btnStop = document.getElementById('btn-audio-stop');
        this.btnClose = document.getElementById('btn-close-audio-editor');

        this.configurarEventos();
    }

    injetarModal() {
        if (document.getElementById('modal-audio-editor')) return;

        const modalHTML = `
        <div id="modal-audio-editor" class="hidden" style="position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.85); z-index:2000; display:flex; justify-content:center; align-items:center; backdrop-filter: blur(5px);">
            <div style="background:#161623; width:900px; height:600px; border-radius:12px; border:1px solid #4ecdc4; display:flex; flex-direction:column; overflow:hidden; box-shadow: 0 0 30px rgba(78, 205, 196, 0.15);">
                <!-- Header -->
                <div style="padding:20px; background:#1a1a2e; border-bottom:1px solid #2a2a40; display:flex; justify-content:space-between; align-items:center;">
                    <h2 style="margin:0; color:#4ecdc4; font-size:20px; display:flex; align-items:center; gap:10px;">
                        <span>🎵</span> Editor de Áudio
                    </h2>
                    <button id="btn-close-audio-editor" style="background:none; border:none; color:#666; font-size:24px; cursor:pointer; transition:color 0.2s;">✕</button>
                </div>
                
                <!-- Body -->
                <div style="flex:1; display:flex; overflow:hidden;">
                    <!-- Left: List -->
                    <div style="width:300px; background:#111; border-right:1px solid #2a2a40; display:flex; flex-direction:column;">
                        <div style="padding:15px; border-bottom:1px solid #2a2a40;">
                            <input type="text" id="audio-search" placeholder="🔍 Buscar áudio..." style="width:100%; background:#1a1a2e; border:1px solid #333; color:#eee; padding:8px 12px; border-radius:6px; outline:none;">
                        </div>
                        <div id="audio-list" style="flex:1; overflow-y:auto; padding:10px;">
                            <!-- Items generated by JS -->
                        </div>
                    </div>

                    <!-- Right: Editor -->
                    <div style="flex:1; padding:30px; background:#161623; display:flex; flex-direction:column; gap:20px; position:relative;">
                        
                        <!-- Empty State -->
                        <div id="audio-editor-empty" style="position:absolute; inset:0; display:flex; flex-direction:column; justify-content:center; align-items:center; color:#444;">
                            <span style="font-size:48px; opacity:0.3;">🎵</span>
                            <p>Selecione um áudio para editar</p>
                        </div>

                        <!-- Content State -->
                        <div id="audio-editor-content" style="display:none; flex-direction:column; gap:20px;">
                            <!-- Info Card -->
                            <div style="background:#1a1a2e; padding:20px; border-radius:8px; border:1px solid #2a2a40; display:flex; align-items:center; gap:15px;">
                                <div style="width:50px; height:50px; background:#4ecdc4; border-radius:8px; display:flex; justify-content:center; align-items:center; font-size:24px; color:#1a1a2e;">
                                    🎵
                                </div>
                                <div>
                                     <h3 id="audio-selected-name" style="margin:0 0 5px 0; color:#fff; font-size:18px;">Nome do Audio</h3>
                                     <div id="audio-selected-id" style="color:#666; font-size:11px; font-family:monospace;">ID: ...</div>
                                </div>
                            </div>

                            <!-- Controls -->
                            <div style="display:grid; grid-template-columns: 1fr 1fr; gap:20px;">
                                <!-- Properties -->
                                <div style="background:#1a1a2e; padding:20px; border-radius:8px; border:1px solid #2a2a40;">
                                    <div style="color:#4ecdc4; font-size:12px; font-weight:bold; margin-bottom:15px; text-transform:uppercase;">Propriedades</div>
                                    
                                    <label style="display:block; color:#aaa; font-size:12px; margin-bottom:8px;">Volume Global (Master Gain)</label>
                                    <div style="display:flex; align-items:center; gap:15px;">
                                        <input type="range" id="audio-vol-slider" min="0" max="2" step="0.1" value="1" style="flex:1; cursor:pointer;">
                                        <span id="audio-vol-val" style="width:40px; text-align:right; color:#fff; font-weight:bold;">1.0</span>
                                    </div>
                                    <p style="font-size:10px; color:#555; margin-top:10px;">
                                        * Ajusta o volume base deste asset em todo o jogo. Multiplica com volumes de scripts.
                                    </p>

                                    <!-- Replace File -->
                                    <div style="margin-top:15px; padding-top:15px; border-top:1px solid #333;">
                                        <label style="display:block; color:#aaa; font-size:12px; margin-bottom:8px;">Arquivo Fonte</label>
                                        <button id="btn-audio-replace" style="width:100%; background:#e67e22; border:none; color:white; padding:8px; border-radius:4px; cursor:pointer; font-size:12px; font-weight:bold;">
                                            📂 Substituir Arquivo
                                        </button>
                                        <input type="file" id="inp-audio-replace" accept="audio/*" style="display:none;">
                                    </div>
                                </div>

                                <!-- Preview -->
                                <div style="background:#1a1a2e; padding:20px; border-radius:8px; border:1px solid #2a2a40;">
                                     <div style="color:#4ecdc4; font-size:12px; font-weight:bold; margin-bottom:15px; text-transform:uppercase;">Preview</div>
                                     <div style="display:flex; gap:10px; margin-bottom:15px;">
                                         <button id="btn-audio-play" style="flex:1; background:#2ecc71; border:none; color:#1a1a2e; padding:10px; border-radius:6px; cursor:pointer; font-weight:bold; display:flex; align-items:center; justify-content:center; gap:5px;">
                                            <span>▶</span> Tocar
                                         </button>
                                         <button id="btn-audio-stop" style="flex:1; background:#e74c3c; border:none; color:white; padding:10px; border-radius:6px; cursor:pointer; font-weight:bold; display:flex; align-items:center; justify-content:center; gap:5px;">
                                            <span>⏹</span> Parar
                                         </button>
                                     </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        `;
        document.body.insertAdjacentHTML('beforeend', modalHTML);
    }

    configurarEventos() {
        this.btnClose.addEventListener('click', () => this.fechar());

        // Fechar ao clicar fora (backdrop)
        this.modal.addEventListener('click', (e) => {
            if (e.target === this.modal) this.fechar();
        });

        this.search.addEventListener('input', () => this.renderizarLista());

        this.sliderVol.addEventListener('input', (e) => {
            const val = parseFloat(e.target.value);
            this.valVol.textContent = val.toFixed(1);

            if (this.selectedAsset) {
                this.editor.assetManager.atualizarAsset(this.selectedAsset.id, { volume: val });

                // Atualizar preview em tempo real se estiver tocando
                if (this.previewAudio) {
                    // Update preview volume (HTML5 Audio or WebAudio) if possible
                    // Simplified: just update property, next play will catch it. 
                    // Or access preview object directly if stored.
                    if (this.previewAudio.setVolume) {
                        this.previewAudio.setVolume(val); // Assuming we returned a controller
                    } else if (this.previewAudio.volume !== undefined) {
                        this.previewAudio.volume = Math.min(1.0, val); // HTML5 limit
                    }
                }
            }
        });

        // Replace File Logic
        const btnReplace = document.getElementById('btn-audio-replace');
        const inpReplace = document.getElementById('inp-audio-replace');

        if (btnReplace && inpReplace) {
            btnReplace.addEventListener('click', () => inpReplace.click());

            inpReplace.addEventListener('change', (e) => {
                const file = e.target.files[0];
                if (file && this.selectedAsset) {
                    const reader = new FileReader();
                    reader.onload = (evt) => {
                        const result = evt.target.result;
                        this.editor.assetManager.atualizarAsset(this.selectedAsset.id, { source: result });
                        this.editor.log(`Arquivo de áudio substituído: ${file.name}`, 'success');
                        this.pararPreview();
                    };
                    reader.readAsDataURL(file);
                }
                e.target.value = '';
            });
        }

        this.btnPlay.addEventListener('click', () => this.tocarPreview());
        this.btnStop.addEventListener('click', () => this.pararPreview());
    }

    abrir() {
        this.modal.classList.remove('hidden');
        this.modal.style.display = 'flex'; // Ensure flex
        this.renderizarLista();
    }

    fechar() {
        this.modal.classList.add('hidden');
        this.modal.style.display = 'none';
        this.pararPreview();
        this.selectedAsset = null;
        this.contentArea.style.display = 'none';
        this.emptyArea.style.display = 'flex';
    }

    renderizarLista() {
        this.lista.innerHTML = '';
        const termo = this.search.value.toLowerCase();

        // Filtrar apenas audios
        const audios = this.assetManager.assets.sons.filter(a =>
            a.nome.toLowerCase().includes(termo)
        );

        audios.forEach(asset => {
            const item = document.createElement('div');
            const isSelected = this.selectedAsset?.id === asset.id;

            item.style.cssText = `
                padding: 10px;
                margin-bottom: 5px;
                background: ${isSelected ? '#3498db' : '#1a1a2e'};
                border: 1px solid ${isSelected ? '#3498db' : '#333'};
                border-radius: 6px;
                cursor: pointer;
                display: flex;
                align-items: center;
                gap: 10px;
                transition: all 0.2s;
            `;

            if (!isSelected) {
                item.onmouseover = () => item.style.borderColor = '#555';
                item.onmouseout = () => item.style.borderColor = '#333';
            }

            item.innerHTML = `
                <div style="font-size:16px;">🎵</div>
                <div style="flex:1; overflow:hidden;">
                    <div style="font-size:12px; color:${isSelected ? '#fff' : '#ddd'}; font-weight:bold; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">${asset.nome}</div>
                    <div style="font-size:10px; color:${isSelected ? '#eee' : '#666'};">${asset.id}</div>
                </div>
            `;

            item.onclick = () => this.selecionarAsset(asset);
            this.lista.appendChild(item);
        });

        if (audios.length === 0) {
            this.lista.innerHTML = '<div style="padding:10px; color:#555; text-align:center; font-size:12px;">Nenhum áudio encontrado.</div>';
        }
    }

    selecionarAsset(asset) {
        this.selectedAsset = asset;
        this.pararPreview();
        this.renderizarLista(); // Update selection highlight

        // Update UI
        this.contentArea.style.display = 'flex';
        this.emptyArea.style.display = 'none';

        this.lblNome.textContent = asset.nome;
        this.lblId.textContent = asset.id;

        const vol = (asset.volume !== undefined) ? asset.volume : 1.0;
        this.sliderVol.value = vol;
        this.valVol.textContent = vol.toFixed(1);
    }

    tocarPreview() {
        if (!this.selectedAsset || !window.AudioManager) return;

        this.pararPreview();

        // Usar o AssetsGlobal para ter o buffer ou source
        // O AudioManager já aplica o volume global que acabamos de salvar no 'input' event
        // Mas para garantir, passamos o volume 1.0 (o AudioManager multiplica pelo meta)

        // Pequena correcao: AudioManager.play retorna objeto { stop, setVolume } se implementamos isso anteriormente
        // Vamos checar a implementacao do AudioManager.play

        try {
            const ctrl = window.AudioManager.play(this.selectedAsset.id, 1.0, false);
            if (ctrl && ctrl.stop) {
                this.previewAudio = ctrl;
            }
        } catch (e) {
            console.error("Erro no preview:", e);
        }
    }

    pararPreview() {
        if (this.previewAudio) {
            if (this.previewAudio.stop) this.previewAudio.stop();
            else if (this.previewAudio.pause) this.previewAudio.pause(); // Fallback
            this.previewAudio = null;
        }
    }
}
